import * as React from "react";

export const onRenderBody = ({ setHeadComponents }) => {
    setHeadComponents([
        <link 
            rel="preload"
            href="/fonts/01db325a7f899fa2d4ada84bf479b288.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowDisplay-Regular"
        />,
        <link 
            rel="preload"
            href="/fonts/87caf42962ee4cd1b299d7e556ac119d.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowDisplay-Medium"
        />,
        <link 
            rel="preload"
            href="/fonts/7192af0d2cedc66b1befc89fc1830ff2.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowDisplay-Bold"
        />,
        <link 
            rel="preload"
            href="/fonts/7192af0d2cedc66b1befc89fc1830ff2.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowDisplay-Bold"
        />,
        <link 
            rel="preload"
            href="/fonts/68a8aa3e4a372c889d564c8fedbc7da2.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowText-Regular"
        />,
        <link 
            rel="preload"
            href="/fonts/b6224fa9faa97ef7cd8bc57dc3c94af9.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowText-RegularItalic"
        />,
        <link 
            rel="preload"
            href="/fonts/132b0e20645f8e571c5e0ea9219be464.woff2"
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
            key="HelveticaNowText-Medium"
        />,
    ])
}